

module Http
  module Wrapper
    module HttpStatusCodes
      HTTP_OK_CODE = 200
      HTTP_CREATED_CODE = 201
      HTTP_BAD_REQUEST_CODE = 400
      HTTP_UNAUTHORIZED_CODE = 401
      HTTP_FORBIDDEN_CODE = 403
      HTTP_NOT_FOUND_CODE = 404
      HTTP_UNPROCESSABLE_ENTITY_CODE = 422
      HTTP_TOO_MANY_REQUEST = 429
      HTTP_INTERNAL_SERVER_ERROR_CODE = 500
      HTTP_BAD_GATEWAY_CODE = 502
      HTTP_SERVICE_UNAVAILABLE_CODE = 503
      HTTP_GATEWAY_TIMEOUT_CODE = 504
    end
  end
end
